
set ( COFFEE_INCLUDE_DIR "${COFFEE_ROOT_DIR}/include" CACHE PATH "" )

set ( COFFEE_CORE_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeCore.a;${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libAndroidCore.a" CACHE STRING "" )

set ( COFFEE_GLEAM_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeGLeam.a" CACHE STRING "" )
set ( COFFEE_ASIO_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeASIO.a" CACHE STRING "" )
set ( COFFEE_OPENAL_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeOpenAL.a" CACHE STRING "" )
set ( COFFEE_SDL2_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeSDL2.a" CACHE STRING "" )
set ( COFFEE_BLAM_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeBlam.a" CACHE STRING "" )
set ( COFFEE_GRAPHICS_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeGraphicsAPI.a" CACHE STRING "" )
set ( COFFEE_IMAGE_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeImage.a" CACHE STRING "" )
set ( COFFEE_ASSIMP_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeAssimp.a" CACHE STRING "" )
set ( COFFEE_WINDOW_X11_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeWindow_X11.a" CACHE STRING "" )
set ( COFFEE_WINDOW_DMX_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeWindow_DMX.a" CACHE STRING "" )
set ( COFFEE_CONTEXT_EGL_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeContext_EGL.a" CACHE STRING "" )
set ( COFFEE_CONTEXT_GLX_LIBRARY "${COFFEE_ROOT_DIR}/lib/${ANDROID_ABI}/libCoffeeContext_GLX.a" CACHE STRING "" )

set ( COFFEE_GRAPHICS_COMMON_LIBRARY
    ${COFFEE_SDL2_LIBRARY}
    ${COFFEE_GRAPHICS_LIBRARY}
    ${COFFEE_WINDOW_X11_LIBRARY}
    ${COFFEE_WINDOW_DMX_LIBRARY}
    ${COFFEE_CONTEXT_EGL_LIBRARY}
    ${COFFEE_CONTEXT_GLX_LIBRARY}
    ${COFFEE_CORE_LIBRARY}
    CACHE STRING "")
set ( COFFEE_GLEAM_COMMON_LIBRARY
    ${COFFEE_GLEAM_LIBRARY}
    ${COFFEE_IMAGE_LIBRARY}
    ${COFFEE_ASSIMP_LIBRARY}
    ${COFFEE_GRAPHICS_COMMON_LIBRARY}
    CACHE STRING "")
