FIND_LIBRARY(
    ZLIBSTATIC_LIBRARY_TMP
    NAMES zlibstatic
    PATHS ${CMAKE_BINARY_DIR}/libs/lib ${COFFEE_ROOT_DIR} ${NATIVE_LIBRARY_DIR}
    PATH_SUFFIXES
    "lib/${CMAKE_LIBRARY_ARCHITECTURE}"
    )

if(NOT TARGET Assimp)
    add_library ( Assimp STATIC IMPORTED )
endif()

set ( ASSIMP_LIBRARY_TMP "${NATIVE_LIBRARY_DIR}/lib/${CMAKE_LIBRARY_ARCHITECTURE}/${CMAKE_STATIC_LIBRARY_PREFIX}assimp${CMAKE_STATIC_LIBRARY_SUFFIX}" )
set ( IRRXML_LIBRARY_TMP "${NATIVE_LIBRARY_DIR}/lib/${CMAKE_LIBRARY_ARCHITECTURE}/${CMAKE_STATIC_LIBRARY_PREFIX}IrrXML${CMAKE_STATIC_LIBRARY_SUFFIX}" )
set ( ZLIBSTATIC_LIBRARY_TMP "${NATIVE_LIBRARY_DIR}/lib/${CMAKE_LIBRARY_ARCHITECTURE}/${CMAKE_STATIC_LIBRARY_PREFIX}zlibstatic${CMAKE_STATIC_LIBRARY_SUFFIX}" )
set ( ASSIMP_INCLUDE_DIR_TMP "${NATIVE_LIBRARY_DIR}/include" )


SET(ASSIMP_INCLUDE_DIR "${ASSIMP_INCLUDE_DIR_TMP}" CACHE PATH "")

get_filename_component ( ASSIMP_LIBRARIES_TMP "${ASSIMP_LIBRARY_TMP}"
    REALPATH )

set ( LINK_LIBS "" )

if(EXISTS "${IRRXML_LIBRARY_TMP}")
    set ( ASSIMP_LIBRARIES_TMP "${ASSIMP_LIBRARIES_TMP};${IRRXML_LIBRARY_TMP}" )

    SET(IRRXML_LIBRARIES "${IRRXML_LIBRARY_TMP}" CACHE FILEPATH "")

    add_library ( IrrXML STATIC IMPORTED )
    set_target_properties ( IrrXML PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${ASSIMP_INCLUDE_DIR_TMP}"
        IMPORTED_LOCATION "${IRRXML_LIBRARIES}"
        )

    list (APPEND LINK_LIBS IrrXML )
endif()

if(EXISTS "${ZLIBSTATIC_LIBRARY_TMP}")
    set ( ASSIMP_LIBRARIES_TMP
        "${ASSIMP_LIBRARIES_TMP};${ZLIBSTATIC_LIBRARY_TMP}" )

    add_library ( ZLibStatic STATIC IMPORTED )
    set_target_properties ( ZLibStatic PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${ASSIMP_INCLUDE_DIR}"
        IMPORTED_LOCATION "${ZLIBSTATIC_LIBRARY_TMP}"
        )
    list (APPEND LINK_LIBS ZLibStatic )
endif()

set_target_properties ( Assimp PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${ASSIMP_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "${LINK_LIBS}"
    IMPORTED_LOCATION "${ASSIMP_LIBRARY_TMP}"
    )

SET(ASSIMP_LIBRARIES "${ASSIMP_LIBRARIES_TMP}" CACHE FILEPATH "")

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(assimp
    REQUIRED_VARS
    ASSIMP_LIBRARIES
    ASSIMP_INCLUDE_DIR)
