set ( OPENSSL_SEARCH_PATHS
    "C:\\OpenSSL-Win64"
    "C:\\OpenSSL-Win32"
    )

find_library ( SSL_CRYPTO_LIBRARY_TMP
    ssleay32

    PATH_SUFFIXES
    lib
	lib/VC
    PATHS
    ${OPENSSL_SEARCH_PATHS}
    )
find_library ( SSL_LIBRARY_TMP
    libeay32

    PATH_SUFFIXES
    lib
	lib/VC
    PATHS
    ${OPENSSL_SEARCH_PATHS}
    )

find_path ( SSL_INCLUDE_DIR_TMP
    ssl.h
    ssl2.h
    ssl3.h

    PATH_SUFFIXES
    include
	include/openssl
    PATHS
    ${OPENSSL_SEARCH_PATHS}
    )

if(DEFINED SSL_CRYPTO_LIBRARY_TMP AND DEFINED SSL_LIBRARY_TMP)
	set ( OPENSSL_LIBRARIES "${SSL_CRYPTO_LIBRARY_TMP};${SSL_LIBRARY_TMP}" CACHE STRING "" )
endif()
if(DEFINED SSL_INCLUDE_DIR_TMP)
	set ( OPENSSL_INCLUDE_DIR "${SSL_INCLUDE_DIR_TMP}/.." CACHE PATH "" )
endif()

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenSSL
    REQUIRED_VARS
    OPENSSL_LIBRARIES
    OPENSSL_INCLUDE_DIR
    )
