allow_fail:
- env: BUILDVARIANT=maemo.armel
- env: BUILDVARIANT=uwp.amd64
- env: BUILDVARIANT=uwp.arm
- env: BUILDVARIANT=coverage
- env: BUILDVARIANT=raspberry.armhf
branches:
- build: true
  deploy: true
  name: master
- build: true
  name: /^testing.*$/
- build: true
  name: /^feature.*$/
coverage: true
display_name: Coffeecutie
makefile_location: toolchain/makers
name: Coffee
platforms:
  android:
  - armv7a.kitkat.gles2
  - armv8a.nougat.gles3
  - armv7a.nougat.gles2
  emscripten:
  - asmjs
  - wasm
  fedora:
  - amd64
  maemo:
  - armel
  osx:
  - osx
  - ios.x86_64
  raspberry:
  - armhf
  steam:
  - amd64
  ubuntu:
  - amd64
  - i686
  - armhf
  windows:
  - win32
  - uwp
script_location: toolchain/ci
secrets:
  appveyor: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
template_location: toolchain/cmake/Templates
version:
  hotfix: 0
  major: 4
  minor: 2
  patch: 0
  release: 18
versionprefix: automated-release-
