allow_fail:
- env: BUILDVARIANT=maemo.armel
- env: BUILDVARIANT=uwp.amd64
- env: BUILDVARIANT=uwp.arm
- env: BUILDVARIANT=raspberry.armhf
branches:
- build: true
  deploy: true
  name: master
- build: true
  name: /^testing.*$/
- build: true
  name: /^feature.*$/
coverage: true
display_name: Coffeecutie
makefile_location: toolchain/makers
name: Coffee
platforms:
  android:
  - armv7a.kitkat.gles2
  - armv8a.nougat.gles3
  emscripten:
  - asmjs
  - wasm
  fedora:
  - amd64
  osx:
  - osx
  - ios.x86_64
  raspberry:
  - armhf
  steam:
  - amd64
  ubuntu:
  - amd64
  - i686
  - armhf
  windows:
  - win32
  - uwp
script_location: toolchain/ci
secrets:
  appveyor: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
template_location: toolchain/cmake/Templates
version:
  hotfix: 2
  major: 4
  minor: 3
  patch: 0
  release: 0
versionprefix: automated-release-

base_dependencies:
  hbirchtree/assimp: v4.1.0
  hbirchtree/glslang: v1
  hbirchtree/shaderc: v1
  hbirchtree/spirv-cross: v1
  hbirchtree/squish: v1
  hbirchtree/bullet: v2.88
  hbirchtree/libav: v1
  hbirchtree/openal: v1.18.2
  hbirchtree/openssl: v1
  hbirchtree/sdl2: v2.0.8
