coverage: true
display_name: Coffeecutie
name: Coffee
script_location: toolchain/ci
template_location: toolchain/cmake/Templates
toolchain:
  source: hbirchtree/coffeecutie-automation-tools
  version: v2.1.1
  emsdk:
    version: 3.1.57
version:
  hotfix: 5
  major: 4
  minor: 4
  patch: 12
  release: 2
versionprefix: rel-
