allow_fail:
  - env: BUILDVARIANT=maemo.armel
  - env: BUILDVARIANT=uwp.amd64
  - env: BUILDVARIANT=uwp.arm
  - env: BUILDVARIANT=coverage
  - env: BUILDVARIANT=raspberry.armhf
name: Coffee
display_name: Coffeecutie
platforms:
    emscripten:
      - asmjs
      - wasm
    ubuntu:
      - amd64
      - i686
      - armhf
    fedora:
      - amd64
    steam:
      - amd64
    android:
      - armv7a
      - armv8a
      - armv7a.kitkat
    maemo:
      - armel
    raspberry:
      - armhf
    osx:
      - osx
      - ios.x86_64
    windows:
      - win32
      - uwp

coverage: true

branches:
  - name: master
    build: true
    deploy: true
  - name: /^testing.*$/
    build: true
  - name: /^feature.*$/
    build: true

secrets:
  appveyor: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
makefile_location: tools/makers
template_location: cmake/Templates
script_location: tools/ci
