allow_fail:
- env: BUILDVARIANT=maemo.armel
- env: BUILDVARIANT=uwp.amd64
- env: BUILDVARIANT=uwp.arm
- env: BUILDVARIANT=raspberry.armhf
- env: BUILDVARIANT=testing.linux.lowfat.debug
- env: BUILDVARIANT=testing.linux.lowfat.release
- env: BUILDVARIANT=testing.linux.release
- env: BUILDVARIANT=ubuntu.i686.gles
base_dependencies:
  hbirchtree/assimp: v4.1.0
  hbirchtree/bullet: v2.88
  hbirchtree/glslang: v1
  hbirchtree/libav: v1
  hbirchtree/openal: v1.18.2
  hbirchtree/openssl: v1
  hbirchtree/sdl2: v2.0.8
  hbirchtree/shaderc: v1
  hbirchtree/spirv-cross: v1
  hbirchtree/squish: v1
branches:
- build: true
  deploy: true
  name: master
- build: true
  name: /^testing.*$/
- build: true
  name: /^feature.*$/
coverage: true
display_name: Coffeecutie
makefile_location: toolchain/makers
name: Coffee
platforms:
  android:
  - armv7a.kitkat.gles2
  - armv8a.nougat.gles3
  emscripten:
  - wasm
  fedora:
  - amd64
  ios:
  - x86_64
  osx:
  - .
  raspberry:
  - armhf
  steam:
  - amd64
  testing:
  - linux
  ubuntu:
    amd64:
    - .
    i686:
    - gles
  uwp:
  - amd64
  win32:
  - amd64
script_location: toolchain/ci
secrets:
  appveyor: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
template_location: toolchain/cmake/Templates
version:
  hotfix: 2
  major: 4
  minor: 3
  patch: 0
  release: 1
versionprefix: automated-release-
