language: cpp
sudo: required
dist: xenial

os:
- linux
- osx
compiler:
  - clang
  - gcc

before_script:
- sudo apt-get update -qq
- sudo apt-get install -qqy libsdl2-dev libopenal-dev cmake ninja-build

script:
- cmake -G"Ninja" -DCOFFEE_BUILD_SNAPPY=ON
- cmake --build . --target install
- cmake --build . --target test

notifications:
  email: true

branches:
  only:
  - master
  - testing
