language: cpp
sudo: required
dist: xenial

os:
- linux
- osx
compiler:
  - clang
  - gcc

before_script:
- tools/travis/install-dependencies.sh

script:
- tools/travis/build.sh

notifications:
  email: true

branches:
  only:
  - master
  - testing
