addons:
  homebrew:
    packages:
    - sdl2
    - cmake
    - python3
    - python
    - jq
    update: true
after_success:
- toolchain/ci/travis-deploy.sh
apt:
  update: true
before_script:
- toolchain/ci/travis-deps.sh
branches:
  only:
  - master
  - /^testing.*$/
  - /^feature.*$/
compiles:
- clang
dist: bionic
env:
  global:
  - MAKEFILE_DIR=toolchain/makers
  - DEPENDENCIES=
  - CONFIGURATION=Release
  matrix:
  - BUILDVARIANT=android.armv7a.kitkat.gles2
  - BUILDVARIANT=android.armv8a.nougat.gles3
  - BUILDVARIANT=emscripten.wasm
  - BUILDVARIANT=fedora.amd64
  - BUILDVARIANT=gamecube
  - BUILDVARIANT=raspberry.armhf
  - BUILDVARIANT=steam.amd64
  - BUILDVARIANT=testing.linux.lowfat.debug
  - BUILDVARIANT=testing.linux.lowfat.release
  - BUILDVARIANT=testing.linux.release
  - BUILDVARIANT=ubuntu.amd64
  - BUILDVARIANT=ubuntu.i686.gles
  - BUILDVARIANT=ios.x86_64
  - BUILDVARIANT=osx
  - BUILDVARIANT=coverage
language: cpp
matrix:
  allow_failures:
  - env: BUILDVARIANT=maemo.armel
  - env: BUILDVARIANT=uwp.amd64
  - env: BUILDVARIANT=uwp.arm
  - env: BUILDVARIANT=raspberry.armhf
  - env: BUILDVARIANT=testing.linux.lowfat.debug
  - env: BUILDVARIANT=testing.linux.lowfat.release
  - env: BUILDVARIANT=testing.linux.release
  - env: BUILDVARIANT=ubuntu.i686.gles
  - env: BUILDVARIANT=gamecube
  - env: BUILDVARIANT=steam.amd64
  exclude:
  - env: BUILDVARIANT=android.armv7a.kitkat.gles2
    os: osx
  - env: BUILDVARIANT=android.armv8a.nougat.gles3
    os: osx
  - env: BUILDVARIANT=emscripten.wasm
    os: osx
  - env: BUILDVARIANT=fedora.amd64
    os: osx
  - env: BUILDVARIANT=gamecube
    os: osx
  - env: BUILDVARIANT=raspberry.armhf
    os: osx
  - env: BUILDVARIANT=steam.amd64
    os: osx
  - env: BUILDVARIANT=testing.linux.lowfat.debug
    os: osx
  - env: BUILDVARIANT=testing.linux.lowfat.release
    os: osx
  - env: BUILDVARIANT=testing.linux.release
    os: osx
  - env: BUILDVARIANT=ubuntu.amd64
    os: osx
  - env: BUILDVARIANT=ubuntu.i686.gles
    os: osx
  - env: BUILDVARIANT=ios.x86_64
    os: linux
  - env: BUILDVARIANT=osx
    os: linux
  - env: BUILDVARIANT=coverage
    os: osx
notifications:
  email: true
os:
- linux
- osx
script:
- toolchain/ci/travis-build.sh
services:
- docker
sudo: required
