language: cpp
sudo: required
dist: xenial

os:
- linux
- osx
compiler:
- clang
- gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

before_script:
- tools/travis/install-dependencies.sh

script:
- tools/travis/build.sh

notifications:
  email: true

branches:
  only:
  - master
  - /^testing.*$/

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "binaries_${TRAVIS_OS_NAME}_${CC}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
