language: cpp
sudo: required
dist: xenial

os:
- linux
- osx
compiler:
  - clang
  - gcc

before_script:
- tools/travis/install-dependencies.sh

script:
- cmake -G"Ninja" -DCOFFEE_BUILD_SNAPPY=ON -DCMAKE_INSTALL_PREFIX=out
- cmake --build . --target install
- cmake --build . --target test

notifications:
  email: true

branches:
  only:
  - master
  - testing
