version: '{build}'
skip_tags: true
branches:
  only:
  - master
  - /testing.*/
  - /feature.*/
configuration:
- Debug
platform: x64
clone_depth: 1
clone_script:
- ps: true
environment:
  INSTALL_DIR: C:\Build\build_*\out\
  BUILD_DIR: C:\project\%APPVEYOR_PROJECT_SLUG%
  CMAKE_BIN: C:\Program Files\CMake\bin\cmake.exe
  MAKEFILE_DIR: tools\makers
install:
- ps: "& tools\ci\appveyor-deps.ps"
build_script:
- ps: "& tools\ci\appveyor-build.ps1"
artifacts:
- path: '*.zip'
  name: Coffee_Win64
deploy:
- provider: GitHub
  release: Appveyor Build $(APPVEYOR_BUILD_NUMBER)
  description: Automatic build by Appveyor
  artifact: Coffee_Win64
  prerelease: true
  on:
    appveyor_repo_tag: true
  auth_token:
      secure: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ

