branches:
  only:
  - master
  - /^testing.*$/
  - /^feature.*$/
before_build:
- ps: tools\ci\appveyor-build.ps1
build:
  project: %BUILD_DIR%\\build_%BUILDVARIANT%\\Coffee.sln
  parallel: true
  verbosity: minimal
clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git
    %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
configuration:
- Debug
deploy_script:
- ps: tools\ci\appveyor-deploy.ps1
environment:
  BUILD_DIR: C:\project\%APPVEYOR_PROJECT_SLUG%
  CMAKE_BIN: cmake.exe
  DEPENDENCIES: ''
  DEPLOY_PATTERNS: ''
  GITHUB_TOKEN:
    secure: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
  MAKEFILE_DIR: tools\makers
  matrix:
  - BUILDVARIANT: uwp.amd64
  - BUILDVARIANT: win32.amd64
  NOBUILD: 1
install:
- ps: tools\ci\appveyor-deps.ps1
matrix:
  allow_failures:
  - BUILDVARIANT: maemo.armel
  - BUILDVARIANT: uwp.amd64
  - BUILDVARIANT: uwp.arm
  - BUILDVARIANT: coverage
platform: x64
skip_tags: true
version: '{build}'
