before_build:
- ps: tools\ci\appveyor-build.ps1
before_deploy:
- cmd: cmake.exe --build %BUILD_DIR% --target install --config %CONFIGURATION%
branches:
  only:
  - master
  - /^testing.*$/
  - /^feature.*$/
build:
  parallel: true
  project: Coffee.sln
  verbosity: minimal
clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git
    %SOURCE_DIR%
- cmd: cd %SOURCE_DIR% && git checkout -qf %APPVEYOR_REPO_COMMIT%
configuration:
- Debug
deploy_script:
- ps: tools\ci\appveyor-deploy.ps1
environment:
  BUILD_DIR: C:\projects\%APPVEYOR_PROJECT_SLUG%
  CMAKE_BIN: cmake.exe
  DEPENDENCIES: ''
  DEPLOY_PATTERNS: ''
  GITHUB_TOKEN:
    secure: 6ME8msH/BDLiEde9wCb9+GQRN4rcAzyu1Vx/wP5yHejedO3vPlrOXHiWqhjNqXrQ
  MAKEFILE_DIR: tools\makers
  NOBUILD: 1
  SAME_BUILD_DIR: 1
  SOURCE_DIR: C:\projects\%APPVEYOR_PROJECT_SLUG%\src
  matrix:
  - BUILDVARIANT: uwp.amd64
  - BUILDVARIANT: win32.amd64
install:
- ps: tools\ci\appveyor-deps.ps1
matrix:
  allow_failures:
  - BUILDVARIANT: maemo.armel
  - BUILDVARIANT: uwp.amd64
  - BUILDVARIANT: uwp.arm
  - BUILDVARIANT: coverage
  - BUILDVARIANT: raspberry.armhf
platform: x64
skip_tags: true
version: '{build}'
