# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
    - examples/*
    - src/*
    - tests/*
    - toolchain/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
  submodules: true
- script: |
    ./toolchain/ci/travis-deps.sh
    ./cb quick-build ubuntu.amd64
  displayName: 'Build Ubuntu amd64'
  condition: eq( variables['Agent.OS'], 'Linux' )
  env:
    CONFIGURATION: Release
    TRAVIS_OS_NAME: linux
- script: |
    ./toolchain/ci/travis-deps.sh
    ./cb quick-build osx
  displayName: 'Build OSX 64-bit'
  condition: eq( variables['Agent.OS'], 'Darwin' )
  env:
    CONFIGURATION: Release
    TRAVIS_OS_NAME: darwin
- powershell: |
    ./toolchain/ci/appveyor-deps.ps1
    ./cb.ps1 quick-build win32.amd64
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
