name: coffeecutie
display_name: Coffeecutie
platforms:
    emscripten:
      - asmjs
      - wasm
    ubuntu:
      - amd64
      - i686
      - armhf
    fedora:
      - amd64
    raspberry:
      - armhf
    steam:
      - amd64
    android:
      - armv7a
      - armv8a
      - armv7a.kitkat
    maemo:
      - armv7a
    osx:
      - osx
      - ios
    windows:
      - win32
      - uwp

branches:
  - name: master
    build: true
    deploy: true
  - name: testing
    build: true

makefile_location: tools/makers
template_location: cmake/Templates
script_location: tools/ci
