set ( CTEST_PROJECT_NAME "CoffeeEngine_${CMAKE_SYSTEM_NAME}" )
set ( CTEST_DROP_METHOD "http" )
set ( CTEST_DROP_SITE "open.cdash.org" )
set ( CTEST_DROP_LOCATION "/submit.php?project=CoffeeEngine" )
set ( CTEST_DROP_SITE_CDASH TRUE )
