#!/bin/bash

OUTPUT_FILE="FindCoffee.cmake"

echo "
#
# Autogenerated by ${0}
# Changes made to this file will NOT be saved
# This find-script will make it easier to add several libraries for external use 
#"

echo '
set ( COFFEE_SEARCH_PATHS
    /usr/local
    /usr
    /opt

    ~/Library/Frameworks
    /Library/Frameworks

    "${COFFEE_ROOT_DIR}"
    "$ENV{COFFEE_ROOT_DIR}"
    )
set ( COFFEE_LIBRARY_SUFFIXES
    lib
    lib64
    lib/${ANDROID_ABI}
    )

find_path ( COFFEE_INCLUDE_DIR_TMP
    coffee/core/coffee.h
    coffee/CCore

    PATHS
    ${COFFEE_ROOT_DIR}
    ${COFFEE_SEARCH_PATHS}

    PATH_SUFFIXES
    include
    )

if(COFFEE_INCLUDE_DIR_TMP)
    set ( COFFEE_INCLUDE_DIR "${COFFEE_INCLUDE_DIR_TMP}" CACHE PATH "" )
endif()'

libnames[0]="CORE"
libnames[1]="GLEAM"
libnames[2]="ASIO"
libnames[3]="OPENAL"
libnames[4]="SDL2"
libnames[5]="BLAM"
libnames[6]="GRAPHICS"
libnames[7]="IMAGE"
libnames[8]="ASSIMP"

soname[0]="Core"
soname[1]="GLeam"
soname[2]="ASIO"
soname[3]="OpenAL"
soname[4]="SDL2"
soname[5]="Blam"
soname[6]="GraphicsAPI"
soname[7]="Image"
soname[8]="Assimp"

for e in $(seq 0 8); do
    echo "
find_library ( COFFEE_${libnames[$e]}_LIBRARY_TMP
    Coffee${soname[$e]}

    PATHS
    \${COFFEE_SEARCH_PATHS}

    PATH_SUFFIXES
    \${COFFEE_LIBRARY_SUFFIXES}
    )

if(COFFEE_${libnames[$e]}_LIBRARY_TMP)
    set ( COFFEE_${libnames[$e]}_LIBRARY \"\${COFFEE_${libnames[$e]}_LIBRARY_TMP}\" CACHE STRING \"\" )
endif()"
done

echo "
if(ANDROID)
    find_library ( COFFEE_ANDROID_LIBRARY_TMP
        AndroidCore

        PATHS
        \${COFFEE_SEARCH_PATHS}

        PATH_SUFFIXES
        \${COFFEE_LIBRARY_SUFFIXES}
        )
    if(COFFEE_ANDROID_LIBRARY_TMP)
        set ( COFFEE_ANDROID_LIBRARY \"\${COFFEE_ANDROID_LIBRARY_TMP}\" CACHE STRING \"\" )
    endif()
endif()

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args (
    Coffee

    REQUIRED_VARS
    COFFEE_INCLUDE_DIR"

for e in $(seq 0 7); do
    echo "    COFFEE_${libnames[$e]}_LIBRARY"
done

echo "    )"
