#!/bin/bash

OUTPUT_FILE="FindCoffee.cmake"

echo "
#
# Autogenerated by ${0}
# Changes made to this file will NOT be saved
# This find-script will make it easier to add several libraries for external use 
#"

echo '
set ( COFFEE_SEARCH_PATHS
    /usr/local
    /usr
    /opt

    ~/Library/Frameworks
    /Library/Frameworks

    "${COFFEE_ROOT_DIR}"
    "$ENV{COFFEE_ROOT_DIR}"
    )
set ( COFFEE_LIBRARY_SUFFIXES
    lib
    lib64
    lib/${ANDROID_ABI}
    )

find_path ( COFFEE_INCLUDE_DIR_TMP
    coffee/core/coffee.h
    coffee/CCore

    PATHS
    ${COFFEE_ROOT_DIR}
    ${COFFEE_SEARCH_PATHS}

    PATH_SUFFIXES
    include
    )

if(COFFEE_INCLUDE_DIR_TMP)
    set ( COFFEE_INCLUDE_DIR "${COFFEE_INCLUDE_DIR_TMP}" CACHE PATH "" )
endif()'

libnames=(
CORE 
GLEAM 
ASIO 
OPENAL
SDL2
BLAM
GRAPHICS
IMAGE
ASSIMP
WINDOW_X11
WINDOW_DMX
CONTEXT_EGL
CONTEXT_GLX
)

soname=(
Core
GLeam
ASIO
OpenAL
SDL2
Blam
GraphicsAPI
Image
Assimp
Window_X11
Window_DMX
Context_EGL
Context_GLX
)

graphics_libs=(
SDL2
GRAPHICS
WINDOW_X11
WINDOW_DMX
CONTEXT_EGL
CONTEXT_GLX
)

gleam_libs=(
GLEAM
IMAGE
ASSIMP
GRAPHICS_COMMON
)

num_libs=${#libnames[@]}
num_libs=$(($num_libs - 1))
num_required_libs=$(($num_libs - 5))

for e in $(seq 0 $num_libs); do
    echo "
find_library ( COFFEE_${libnames[$e]}_LIBRARY_TMP
    Coffee${soname[$e]}

    PATHS
    \${COFFEE_SEARCH_PATHS}

    PATH_SUFFIXES
    \${COFFEE_LIBRARY_SUFFIXES}
    )

if(COFFEE_${libnames[$e]}_LIBRARY_TMP)
    set ( COFFEE_${libnames[$e]}_LIBRARY \"\${COFFEE_${libnames[$e]}_LIBRARY_TMP}\" CACHE STRING \"\" )
endif()
"
done

echo "\
set ( COFFEE_GRAPHICS_COMMON_LIBRARY"

for e in $(seq 0 ${#graphics_libs[@]}); do
    if [[ ! -z ${graphics_libs[$e]} ]]; then
        echo "    \${COFFEE_${graphics_libs[$e]}_LIBRARY}"
    fi
done

echo "\
    CACHE STRING \"\")"

echo "\
set ( COFFEE_GLEAM_COMMON_LIBRARY"

for e in $(seq 0 ${#gleam_libs[@]}); do
    if [[ ! -z ${gleam_libs[$e]} ]]; then
        echo "    \${COFFEE_${gleam_libs[$e]}_LIBRARY}"
    fi
done

echo "\
    CACHE STRING \"\")"

echo "
if(ANDROID)
    find_library ( COFFEE_ANDROID_LIBRARY_TMP
        AndroidCore

        PATHS
        \${COFFEE_SEARCH_PATHS}

        PATH_SUFFIXES
        \${COFFEE_LIBRARY_SUFFIXES}
        )
    if(COFFEE_ANDROID_LIBRARY_TMP)
        set ( COFFEE_ANDROID_LIBRARY \"\${COFFEE_ANDROID_LIBRARY_TMP}\" CACHE STRING \"\" )
    endif()
endif()

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args (
    Coffee

    REQUIRED_VARS
    COFFEE_INCLUDE_DIR"

for e in $(seq 0 $num_required_libs); do
    echo "    COFFEE_${libnames[$e]}_LIBRARY"
done

echo "    )"
