set ( BUILD_AUDIO OFF CACHE BOOL "" )
set ( BUILD_MEDIA OFF CACHE BOOL "" )
set ( BUILD_SDL2 OFF CACHE BOOL "" )
set ( BUILD_TESTS OFF CACHE BOOL "" )

set ( BUILD_ANATIVE ON CACHE BOOL "" )
set ( BUILD_EGL ON CACHE BOOL "" )
set ( BUILD_GLES ON CACHE BOOL "" )
set ( BUILD_GLES_31 ON CACHE BOOL "" )
set ( BUILD_GLES_32 ON CACHE BOOL "" )
set ( BUILD_GL_SOFTWARE_BCN ON CACHE BOOL "" )

