# Disabled features
set ( BUILD_SDL2 OFF CACHE BOOL "" )
set ( BUILD_MEDIA OFF CACHE BOOL "" )
set ( BUILD_OPENAL OFF CACHE BOOL "" )
# Enabled features
set ( BUILD_GLES ON CACHE BOOL "" )
set ( BUILD_GLES_20 ON CACHE BOOL "" )
set ( BUILD_EGL ON CACHE BOOL "" )
set ( BUILD_EGL_DOUBLE_GETPROC ON CACHE BOOL "" )
set ( BUILD_GL_SOFTWARE_BCN ON CACHE BOOL "" )

# Build flags
set ( BEAGLE ON CACHE BOOL "" )

