set ( BUILD_ASSIMP ON CACHE BOOL "" )
set ( BUILD_ASIO ON CACHE BOOL "" )
set ( BUILD_ASSET_TOOLS ON CACHE BOOL "" )
set ( BUILD_DISCORD_RPC ON CACHE BOOL "" )
set ( BUILD_GL_SOFTWARE_BCN ON CACHE BOOL "" )
set ( BUILD_GLEAM ON CACHE BOOL "" )
set ( BUILD_OPENSSL ON CACHE BOOL "" )
set ( BUILD_SDL2 ON CACHE BOOL "" )

set ( GENERATE_APPIMAGE ON CACHE BOOL "" )

set ( MKSQUASH_PROGRAM "/usr/bin/mksquashfs" CACHE STRING "" )
