jenkins:
  build: jenkins/
  hostname: jenkins
  ports:
   - "8000:8000"
   - "50000:50000"
  volumes:
   - /var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
   - /usr/lib/x86_64-linux-gnu/libapparmor.so.1.1.0:/lib/x86_64-linux-gnu/libapparmor.so.1
  command: --prefix=/jenkins
