set(ASSIMP_ROOT_DIR "${ASSIMP_ROOT_DIR}"
    CACHE PATH "Directory to search for Assimp")

FIND_PATH( ASSIMP_INCLUDE_DIR_TMP

    Importer.hpp

    PATHS
    ${NATIVE_LIBRARY_DIR}
    ${CMAKE_BINARY_DIR}/libs/
    ${COFFEE_EXT_LIBRARY_DIR}/assimp/
    ${COFFEE_ROOT_DIR}

    PATH_SUFFIXES include include/assimp
    )

FIND_LIBRARY(
    ASSIMP_LIBRARIES_TMP
    NAMES assimp
    PATHS ${CMAKE_BINARY_DIR}/libs/lib/ ${COFFEE_ROOT_DIR} ${NATIVE_LIBRARY_DIR}
    PATH_SUFFIXES
    64/link lib lib64
    "lib/${CMAKE_LIBRARY_ARCHITECTURE}" # CMake architecture path
    "lib/${ANDROID_ABI}"
    )

FIND_LIBRARY(
    IRRXML_LIBRARIES_TMP
    NAMES IrrXML
    PATHS ${CMAKE_BINARY_DIR}/libs/lib/ ${COFFEE_ROOT_DIR} ${NATIVE_LIBRARY_DIR}
    PATH_SUFFIXES
    64/link lib lib64
    "lib/${CMAKE_LIBRARY_ARCHITECTURE}" # CMake architecture path
    "lib/${ANDROID_ABI}"
    )

IF (ASSIMP_INCLUDE_DIR_TMP AND ASSIMP_LIBRARIES_TMP)
    SET(ASSIMP_FOUND TRUE)

    get_filename_component ( ASSIMP_LIBRARIES_TMP "${ASSIMP_LIBRARIES_TMP}" REALPATH )
    
    if(IRRXML_LIBRARIES_TMP)
        set ( ASSIMP_LIBRARIES_TMP "${ASSIMP_LIBRARIES_TMP};${IRRXML_LIBRARIES_TMP}" )
    endif()

    SET(ASSIMP_LIBRARIES "${ASSIMP_LIBRARIES_TMP}" CACHE FILEPATH "")
    SET(ASSIMP_INCLUDE_DIR "${ASSIMP_INCLUDE_DIR_TMP}/.." CACHE PATH "")
ENDIF (ASSIMP_INCLUDE_DIR_TMP AND ASSIMP_LIBRARIES_TMP)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(assimp REQUIRED_VARS ASSIMP_LIBRARIES ASSIMP_INCLUDE_DIR)
