set(CMAKE_C_FLAGS "-sMEMORY64=1 -sWASM_BIGINT" CACHE STRING "")
set(CMAKE_CXX_FLAGS "-sMEMORY64=1 -sWASM_BIGINT" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS "-sMEMORY64=1 -sWASM_BIGINT" CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/../Platform/Emscripten.cmake")
