set ( CMAKE_SYSTEM_NAME Generic )
set ( CMAKE_SYSTEM_PROCESSOR mips64 )
set ( CMAKE_CROSSCOMPILING 1 )
set ( TOOLCHAIN_PREFIX mips64-elf )

set ( CMAKE_EXECUTABLE_SUFFIX "elf" )

find_program ( C_COMPILER
    ${TOOLCHAIN_PREFIX}-gcc

    PATHS
    ${N64CHAIN_DIR}
    PATH_SUFFIXES
    bin
    )

find_program ( CXX_COMPILER
    ${TOOLCHAIN_PREFIX}-g++

    PATHS
    ${N64CHAIN_DIR}
    PATH_SUFFIXES
    bin
    )

set ( COMMON_FLAGS "-mabicalls" )

set ( CMAKE_C_COMPILER ${C_COMPILER} )
set ( CMAKE_CXX_COMPILER ${CXX_COMPILER} )
set ( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${COMMON_FLAGS}" CACHE STRING "" )
set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMMON_FLAGS}" CACHE STRING "" )
set ( CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lstdc++ -lc -lnosys" CACHE STRING "" )
set ( CMAKE_LIBRARY_ARCHITECTURE "${TOOLCHAIN_PREFIX}" CACHE STRING "" )

set ( N64CHAIN "${N64CHAIN_DIR}" CACHE STRING "" )
set ( N64 ON CACHE BOOL "" )

add_definitions ( -DMIPS64 -DNEN64 -D__N64__ )

