#
# This Dockerfile will create an environment for building against the Steam Runtime as a means of staying portable on Linux
# Any dependencies needed to build will be installed
# The build process will still be performed manually
#
