set ( BUILD_COVERAGE ON  CACHE BOOL "" )
set ( BUILD_ASAN     ON  CACHE BOOL "" )
set ( BUILD_EXAMPLES OFF CACHE BOOL "" )

set ( SKIP_HIGHMEM_TESTS ON CACHE BOOL "" )
set ( SKIP_LINKAGE_TEST  ON CACHE BOOL "" )
set ( SKIP_OPENVR_TEST   ON CACHE BOOL "" )
