set ( BUILD_COVERAGE ON CACHE BOOL "" )
set ( CMAKE_BUILD_TYPE "Debug" CACHE STRING "" )

set ( COFFEE_ASAN ON CACHE BOOL "" )

set ( GENERATE_EXAMPLES OFF CACHE BOOL "" )

set ( SKIP_HIGHMEM_TESTS ON CACHE BOOL "" )
set ( SKIP_LINKAGE_TEST ON CACHE BOOL "" )
set ( SKIP_OPENVR_TEST ON CACHE BOOL "" )
