set ( COFFEE_BUILD_ASSIMP ON CACHE BOOL "" )

set ( SKIP_HIGHMEM_TESTS ON CACHE BOOL "" )

set ( GENERATE_EXAMPLES OFF CACHE BOOL "" )

#set ( COFFEE_VALGRIND_MASSIF ON CACHE BOOL "" )
set ( COFFEE_VALGRIND_MEMCHECK ON CACHE BOOL "" )
#set ( COFFEE_VALGRIND_CALLGRIND ON CACHE BOOL "" )
#set ( COFFEE_VALGRIND_CACHEGRIND ON CACHE BOOL "" )
