set ( COFFEE_BUILD_OPENVR ON CACHE BOOL "" )

set ( OPENSSL_ROOT_DIR "C:/OpenSSL-Win64" CACHE PATH "" )
set ( OPENSSL_SSL_LIBRARY "C:/OpenSSL-Win64/lib/libssl.lib" CACHE FILEPATH "" )
set ( OPENSSL_CRYPTO_LIBRARY "C:/OpenSSL-Win64/lib/libcrypto.lib" CACHE FILEPATH "" )

set ( COFFEE_BUILD_GLES ON CACHE BOOL "" )
set ( COFFEE_BUILD_ANGLE ON CACHE BOOL "" )