set ( BUILD_GLES    ON  CACHE BOOL "" )

set ( BUILD_ASIO    OFF CACHE BOOL "" )
set ( BUILD_ASSIMP  OFF CACHE BOOL "" )
set ( BUILD_AUDIO   OFF CACHE BOOL "" )
set ( BUILD_OPENAL  OFF CACHE BOOL "" )
set ( BUILD_OPENSSL OFF CACHE BOOL "" )

