set ( BUILD_ASSIMP  OFF CACHE BOOL "" )

set ( BUILD_OPENSSL OFF CACHE BOOL "" )
set ( BUILD_OPENAL  OFF CACHE BOOL "" )

set ( SKIP_HIGHMEM_TESTS  ON CACHE BOOL "" )
set ( SKIP_LINKAGE_TEST   ON CACHE BOOL "" )

