CREATE TABLE BUILDREPORTS(
    REPORT_ID INT PRIMARY KEY NOT NULL,
    SERVERID TEXT[60] NOT NULL,
    BUILD_HASH TEXT[60] NOT NULL,
    PLATFORM_ID TEXT[60] NOT NULL,
    BUILD_STATUS INT,
    ERROR_OUTPUT BLOB
);
