=toolchain-dir: $(cmake.src)/toolchain/cmake
+cmake-opts:
  - -DCMAKE_BUILD_TYPE=$(build-type)
  - -DCMAKE_INSTALL_PREFIX=$(cmake.install)/$(target-name)
  - -DBUILD_BINARIES=$(env:GENERATE_PROGRAMS)
  - -DSKIP_GRAPHIC_TESTS=$(env:HEADLESS)
+container-opts:
  - -v $(project.src):$(container.src):ro
  - -v $(project.install):$(container.install):rw
  - -v $(project.build)/$(target-name):$(container.build):rw
  - -v $(lib.root):$(lib.target):ro
  - --workdir "$(env:CMAKE_BUILD_DIR)"
.*tools:
  +cmake-opts:
    - -DBUILD_UTILITIES=ON
    - -DBUILD_EXAMPLES=OFF
    - -DBUILD_TESTS=OFF
    - -DGENERATE_FLATPAK=OFF
    - -DGENERATE_SNAPPY=OFF
    - -DGENERATE_APPIMAGE=ON
    - -DBUILD_ETC2COMP=ON
    - -DBUILD_SDL2=OFF
    - -DBUILD_HEADFUL=OFF
(ios|android).*:
  +cmake-opts:
    - -DBUILD_EGL=ON
osx:
  +cmake-opts:
    - -DBUILD_ETC2COMP=ON
ios.*:
  +cmake-opts:
    - -DBUILD_GLKIT=ON
    - -DBUILD_SDL2=OFF
    - -DBUILD_GLES=ON
    - -DBUILD_GLES_20=ON
coverage:
  =target: multi.twostage
  =cmake-target:
    - all
    - CoverageTest
testing.linux.*:
  =target: multi.twostage
  =cmake-target:
    - all
    - test
.*ubuntu.amd64.*:
  +cmake-opts:
    - -DMKSQUASH_PROGRAM=/usr/bin/mksquashfs
    - -DGENERATE_APPIMAGE=ON
.*android.*:
  +cmake-opts:
    - -DBUILD_GLES=ON
    - -DBUILD_ANATIVE=ON
    - -DBUILD_TESTS=OFF
    - -DBUILD_SDL2=OFF
  .*(gingerbread|v19).*:
    +cmake-opts:
      - -DBUILD_GLES_20=ON
  ^((?!\$\(shell\)).)*$:
    =target: multi.ensureinstall
  =cmake-target:
    - AndroidPackage
emscripten.*:
  +cmake-opts:
    - -DBUILD_SDL2=ON
    - -DBUILD_OPENSSL=OFF
    - -DBUILD_AUDIO=OFF
    - -DBUILD_GLES=ON
    - -DBUILD_GLES_20=ON
    - -DGENERATE_HTML=ON
gamecube.*:
  +cmake-opts:
    - -DBUILD_LIBOGC=ON
    - -DBUILD_ASIO=OFF
    - -DBUILD_AUDIO=OFF
    - -DBUILD_SDL2=OFF
    - -DBUILD_OPENGL=OFF
    - -DBUILD_GRAPHICS_COMMON=OFF
    - -DBUILD_BLAM=OFF
    - -DBUILD_GX=ON
.*maemo.*:
  +cmake-opts:
    - -DBUILD_SDL2=OFF
    - -DBUILD_X11=ON
    - -DBUILD_EGL=ON
.*(ubuntu|fedora|coverage|testing.linux|docs|steam|osx).*:
  +cmake-opts:
    - -DBUILD_ASSIMP=ON
(ubuntu.amd64|osx).*:
  +cmake-opts:
    - -DBUILD_DISCORD_RPC=ON

.*beaglebone.*:
  +cmake-opts:
    - -DBUILD_GLES=ON
    - -DBUILD_GLES_20=ON
    - -DBUILD_OPENAL=OFF
    - -DBUILD_OPENSSL=OFF
    - -DBUILD_SDL2=OFF
    - -DBUILD_EGL=ON

