=toolchain-dir: $(cmake.src)/toolchain/cmake
+cmake-opts:
  - -DCMAKE_BUILD_TYPE=$(build-type)
  - -DCMAKE_INSTALL_PREFIX=$(cmake.install)/$(target-name)
  - -DBUILD_BINARIES=$(env:GENERATE_PROGRAMS)
  - -DSKIP_GRAPHIC_TESTS=$(env:HEADLESS)
+container-opts:
    #- -v $(dependencies.native-libs.root):$(dependencies.native-libs.target):ro
  - -v $(project.src):$(container.src):ro
  - -v $(project.install):$(container.install):rw
  - -v $(project.build)/$(target-name):$(container.build):rw
  - -v $(lib.root):$(lib.target):ro
  - --workdir "$(env:CMAKE_BUILD_DIR)"
.*tools:
  +cmake-opts:
    - -DBUILD_UTILITIES=ON
    - -DBUILD_EXAMPLES=OFF
    - -DBUILD_TESTS=OFF
    - -DGENERATE_FLATPAK=OFF
    - -DGENERATE_SNAPPY=OFF
    - -DGENERATE_APPIMAGE=ON
    - -DBUILD_ETC2COMP=ON
    - -DBUILD_SDL2=OFF
    - -DBUILD_HEADFUL=OFF
(ios|android).*:
  +cmake-opts:
    - -DBUILD_EGL=ON
osx:
  +cmake-opts:
    - -DBUILD_ETC2COMP=ON
ios.*:
  +cmake-opts:
    - -DBUILD_GLKIT=ON
    - -DBUILD_SDL2=OFF
    - -DBUILD_GLES=ON
    - -DBUILD_GLES_20=ON
coverage:
  =target: multi.twostage
  =cmake-target:
    - all
    - CoverageTest
testing.linux.*:
  =target: multi.twostage
  =cmake-target:
    - all
    - test
.*ubuntu.amd64.*:
  +cmake-opts:
    - -DMKSQUASH_PROGRAM=/usr/bin/mksquashfs
    - -DAPPIMAGE_RUNTIME_BINARY=$(env:NATIVE_LIBRARY_DIR)/$(build.prettyname)/util/x86_64-linux-gnu/runtime
    - -DGENERATE_APPIMAGE=ON
.*android.*:
  +cmake-opts:
    - -DBUILD_GLES=ON
    - -DBUILD_GLES_20=$(android.gles20)
    - -DBUILD_ANATIVE=ON
    - -DBUILD_TESTS=OFF
    - -DBUILD_SDL2=OFF
  ^((?!\$\(shell\)).)*$:
    =target: multi.ensureinstall
  =cmake-target:
    - AndroidPackage
emscripten.*:
  +cmake-opts:
    - -DBUILD_SDL2=ON
    - -DBUILD_OPENSSL=OFF
    - -DBUILD_AUDIO=OFF
    - -DBUILD_GLES=ON
    - -DBUILD_GLES_20=ON
    - -DGENERATE_HTML=ON
gamecube.*:
  +cmake-opts:
    - -DBUILD_LIBOGC=ON
    - -DBUILD_ASIO=OFF
    - -DBUILD_AUDIO=OFF
    - -DBUILD_SDL2=OFF
    - -DBUILD_OPENGL=OFF
    - -DBUILD_GRAPHICS_COMMON=OFF
    - -DBUILD_BLAM=OFF
    - -DBUILD_CPP14=ON
.*maemo.*:
  +cmake-opts:
    - -DBUILD_SDL2=OFF
    - -DBUILD_X11=ON
    - -DBUILD_EGL=ON
.*(ubuntu|fedora|coverage|testing.linux|android|docs|steam|raspberry|emscripten|osx).*:
  +cmake-opts:
    - -DBUILD_ASSIMP=ON
