set ( GAMECUBE ON CACHE BOOL "" )

set ( TOOLCHAIN_PREFIX "powerpc-eabi" )
set ( DEVKITPPC_PATH "$ENV{DEVKITPPC_PATH}" CACHE STRING "DevkitPPC path" )

if(CMAKE_TOOLCHAIN_FILE)
    # Stub warnings, dude
endif()

set ( CMAKE_SYSTEM_NAME Nintendo )
set ( CMAKE_SYSTEM_VERSION 1 )

add_definitions(-D__GAMECUBE__)

set ( CMAKE_FIND_ROOT_PATH "${DEVKITPPC_PATH}" )

set ( CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-gcc" )
set ( CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}-g++" )

set ( CMAKE_AR "${TOOLCHAIN_PREFIX}-ar" CACHE STRING "" )
set ( CMAKE_AS "${TOOLCHAIN_PREFIX}-as" CACHE STRING "" )
set ( CMAKE_LINKER "${TOOLCHAIN_PREFIX}-ld" CACHE STRING "" )
set ( CMAKE_STRIP "${TOOLCHAIN_PREFIX}-strip" CACHE STRING "" )
set ( CMAKE_NM "${TOOLCHAIN_PREFIX}-nm" CACHE STRING "" )
set ( CMAKE_RANLIB "${TOOLCHAIN_PREFIX}-ranlib" CACHE STRING "" )
set ( CMAKE_OBJCOPY "${TOOLCHAIN_PREFIX}-objcopy" CACHE STRING "" )

SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")
SET(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "")

set ( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set ( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set ( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )

include_directories ( 
    "${DEVKITPPC_PATH}/powerpc-eabi/include" 
    "${DEVKITPPC_PATH}/powerpc-eabi/include/c++/4.8.2" 
    "${DEVKITPPC_PATH}/powerpc-eabi/include" 
    )


