/*
 *
 * This file is all about covering the files wanted for export to C
 *
 * The code will be auto-generated by the LCodeGenerator tool
 *
 */

/* Big headers */
#include <coffee/core/CProfiling>
#include <coffee/core/CFiles>

#include <coffee/core/types/vector_types.h>

#include <coffee/core/argument_handling.h>
#include <coffee/core/internal_state.h>

