#!/usr/bin/env python3
"""Crunch source assets into typed C++ arrays.

Unlike the VFS blob path (resources-to-source.py), this emits *typed* constexpr
data -- pixels in their upload format, vertices in a struct -- so an asset can
go straight to the GPU without a filesystem round-trip or a parse step.

Driven by a "crunch" entry in a resources.json:

    "crunch": {
        "output":    "crunched/loading_screen.h",  // under --include-output
        "namespace": "blam::loading",
        "text": [
            {"source": "shaders/blit.glsl", "name": "blit_source"}
        ],
        "textures": [
            {"source": "textures/noise.png", "name": "noise",
             "format": "r8", "channel": "r"},
            {"source": "textures/parts.png", "name": "parts",
             "format": "rgb565"}
        ],
        "meshes": [
            {"source": "mesh/loading.obj", "name": "loading"}
        ]
    }

Text entries become a std::string_view over a raw literal -- inline shader
sources kept in a real file. Texture formats are r8, rgb565 and rgba8. Meshes
emit one crunch::mesh_bounds (a bounding box) per file plus a vertex and index
array per object in it; positions and texcoords stay f32, normals pack to
snorm u16. Can also be run on its own:

    asset_crunch.py --root <asset dir> --output <include dir>
"""

import struct
import zlib
from os import environ, makedirs
from os.path import basename, dirname, exists, splitext

VERBOSE = environ.get('VERBOSE', '') not in ('', '0')


def log(*args, **kwargs):
    if VERBOSE:
        print(*args, **kwargs)


# Bumping this invalidates nothing on its own, but generated headers carry it
# so a stale header is visible in a diff.
FORMAT_VERSION = 1

TYPES_HEADER = '''#pragma once

/* Generated by toolchain/desktop/asset_crunch.py -- do not edit. */

#include <array>
#include <string_view>

#include <peripherals/libc/types.h>
#include <peripherals/typing/vectors/vector_types.h>

namespace crunch {

using libc_types::f32;
using libc_types::u16;
using libc_types::u32;
using libc_types::u8;
using typing::vector_types::tvec2;
using typing::vector_types::tvec3;
using typing::vector_types::Vecf2;
using typing::vector_types::Vecf3;

enum class pixel_format
{
    r8,      /*!< one channel, GL_R8 / GL_RED + GL_UNSIGNED_BYTE */
    rgb565,  /*!< one u16 per pixel, GL_RGB + GL_UNSIGNED_SHORT_5_6_5 */
    rgba8,   /*!< four bytes per pixel, GL_RGBA8 */
};

struct texture_desc
{
    u32          width;
    u32          height;
    pixel_format format;
};

/*!
 * \\brief A crunched vertex.
 *
 * Position and texcoord are plain f32 and upload as-is. The normal is snorm
 * u16 over [-1, 1] -- it is bounded by definition, so it costs nothing to
 * pack -- and decode_normal() unpacks it. Attribute offsets are 0, 12 and 20;
 * the trailing two bytes are padding, so the stride is 28.
 */
struct vertex
{
    Vecf3      position;
    Vecf2      texcoord;
    tvec3<u16> normal;
};

static_assert(sizeof(vertex) == 28, "crunch::vertex layout changed");

/*!
 * \\brief Bounding box of a crunched mesh, over every object in the source
 *        file. Informational -- vertices need no decode -- but handy for
 *        framing a camera or sizing a bounding volume.
 */
struct mesh_bounds
{
    Vecf3 position_min;
    Vecf3 position_max;
    Vecf2 texcoord_min;
    Vecf2 texcoord_max;
};

inline constexpr f32 unorm16 = 1.0f / 65535.0f;

inline Vecf3 decode_normal(vertex const& v)
{
    return Vecf3(v.normal) * unorm16 * 2.0f - 1.0f;
}

} // namespace crunch
'''


class CrunchError(Exception):
    pass


# -- PNG --------------------------------------------------------------------

def read_png(path: str):
    """Decode a non-interlaced 8-bit PNG to (width, height, channels, bytes)."""
    data = open(path, 'rb').read()
    if data[:8] != b'\x89PNG\r\n\x1a\n':
        raise CrunchError(f'{path}: not a PNG')
    idat = b''
    palette = None
    trns = None
    header = None
    off = 8
    while off + 8 <= len(data):
        length, = struct.unpack('>I', data[off:off + 4])
        kind = data[off + 4:off + 8]
        body = data[off + 8:off + 8 + length]
        if kind == b'IHDR':
            header = struct.unpack('>IIBBBBB', body)
        elif kind == b'PLTE':
            palette = body
        elif kind == b'tRNS':
            trns = body
        elif kind == b'IDAT':
            idat += body
        elif kind == b'IEND':
            break
        off += 12 + length
    if header is None:
        raise CrunchError(f'{path}: no IHDR')
    width, height, depth, color, _, _, interlace = header
    if depth != 8:
        raise CrunchError(f'{path}: only 8-bit PNGs are supported, got {depth}')
    if interlace != 0:
        raise CrunchError(f'{path}: interlaced PNGs are not supported')
    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}.get(color)
    if channels is None:
        raise CrunchError(f'{path}: unhandled color type {color}')

    raw = zlib.decompress(idat)
    stride = width * channels
    out = bytearray(height * stride)
    prev = bytearray(stride)
    pos = 0
    for y in range(height):
        filt = raw[pos]
        pos += 1
        line = bytearray(raw[pos:pos + stride])
        pos += stride
        if filt == 1:
            for i in range(channels, stride):
                line[i] = (line[i] + line[i - channels]) & 0xFF
        elif filt == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xFF
        elif filt == 3:
            for i in range(stride):
                left = line[i - channels] if i >= channels else 0
                line[i] = (line[i] + ((left + prev[i]) >> 1)) & 0xFF
        elif filt == 4:
            for i in range(stride):
                a = line[i - channels] if i >= channels else 0
                b = prev[i]
                c = prev[i - channels] if i >= channels else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        elif filt != 0:
            raise CrunchError(f'{path}: bad row filter {filt}')
        out[y * stride:(y + 1) * stride] = line
        prev = line

    if color == 3:
        if palette is None:
            raise CrunchError(f'{path}: palettized without PLTE')
        expanded = bytearray(width * height * 4)
        for i, index in enumerate(out):
            expanded[i * 4:i * 4 + 3] = palette[index * 3:index * 3 + 3]
            expanded[i * 4 + 3] = trns[index] if trns and index < len(trns) else 0xFF
        return width, height, 4, bytes(expanded)
    return width, height, channels, bytes(out)


def _channel(pixels: bytes, channels: int, index: int):
    return pixels[index::channels] if channels > 1 else pixels


def quantize_texture(pixels: bytes, channels: int, fmt: str, source_channel: str):
    """Return (element C++ type, list of integer literals) for a pixel format."""
    if fmt == 'r8':
        lane = {'r': 0, 'g': 1, 'b': 2, 'a': 3}[source_channel]
        if lane >= channels:
            raise CrunchError(f'source has no {source_channel} channel')
        return 'libc_types::u8', list(_channel(pixels, channels, lane))
    if fmt == 'rgb565':
        if channels < 3:
            raise CrunchError('rgb565 needs an RGB source')
        red = _channel(pixels, channels, 0)
        green = _channel(pixels, channels, 1)
        blue = _channel(pixels, channels, 2)
        return 'libc_types::u16', [
            ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            for r, g, b in zip(red, green, blue)]
    if fmt == 'rgba8':
        if channels == 4:
            return 'libc_types::u8', list(pixels)
        out = []
        for i in range(0, len(pixels), channels):
            px = pixels[i:i + channels]
            if channels == 1:
                out += [px[0], px[0], px[0], 0xFF]
            elif channels == 2:
                out += [px[0], px[0], px[0], px[1]]
            else:
                out += [px[0], px[1], px[2], 0xFF]
        return 'libc_types::u8', out
    raise CrunchError(f'unknown texture format {fmt}')


# -- OBJ --------------------------------------------------------------------

def read_obj(path: str):
    """Parse an OBJ into [(object name, [(pos, normal, uv)], [indices])]."""
    positions, texcoords, normals = [], [], []
    objects = []
    current = None

    def start(name):
        objects.append((name, {}, [], []))  # name, lookup, vertices, indices
        return objects[-1]

    for line in open(path):
        parts = line.split()
        if not parts:
            continue
        tag = parts[0]
        if tag == 'v':
            positions.append(tuple(float(v) for v in parts[1:4]))
        elif tag == 'vt':
            texcoords.append(tuple(float(v) for v in parts[1:3]))
        elif tag == 'vn':
            normals.append(tuple(float(v) for v in parts[1:4]))
        elif tag in ('o', 'g'):
            current = start(parts[1] if len(parts) > 1 else 'mesh')
        elif tag == 'f':
            if current is None:
                current = start(splitext(basename(path))[0])
            _, lookup, verts, indices = current
            corners = []
            for corner in parts[1:]:
                if corner not in lookup:
                    fields = (corner.split('/') + ['', ''])[:3]

                    def pick(source, field, fallback):
                        if not field:
                            return fallback
                        index = int(field)
                        return source[index - 1 if index > 0 else len(source) + index]

                    lookup[corner] = len(verts)
                    verts.append((
                        pick(positions, fields[0], (0.0, 0.0, 0.0)),
                        pick(normals, fields[2], (0.0, 0.0, 1.0)),
                        pick(texcoords, fields[1], (0.0, 0.0))))
                corners.append(lookup[corner])
            # Fan-triangulate; Blender emits triangles, others may not.
            for i in range(1, len(corners) - 1):
                indices += [corners[0], corners[i], corners[i + 1]]

    return [(name, verts, indices) for name, _, verts, indices in objects if indices]


def _bounds(values, count):
    return ([min(v[i] for v in values) for i in range(count)],
            [max(v[i] for v in values) for i in range(count)])


def quantize_mesh(objects: list):
    """Keep positions and texcoords as f32; pack normals to snorm u16."""
    every_vertex = [v for _, verts, _ in objects for v in verts]
    if not every_vertex:
        raise CrunchError('mesh has no vertices')
    pos_min, pos_max = _bounds([v[0] for v in every_vertex], 3)
    uv_min, uv_max = _bounds([v[2] for v in every_vertex], 2)

    def snorm(value):
        return max(0, min(65535, int(round((value * 0.5 + 0.5) * 65535.0))))

    crunched = []
    for name, verts, indices in objects:
        if len(verts) > 65536:
            raise CrunchError(f'{name}: {len(verts)} vertices exceeds u16 indices')
        out = [(pos, [snorm(normal[i]) for i in range(3)], uv)
               for pos, normal, uv in verts]
        crunched.append((name, out, indices))
    return (pos_min, pos_max, uv_min, uv_max), crunched


# -- emit -------------------------------------------------------------------

def identifier(name: str):
    out = ''.join(c if c.isalnum() else '_' for c in name).lower()
    return out if not out[0].isdigit() else '_' + out


def _rows(values, per_row, width):
    for i in range(0, len(values), per_row):
        yield '    ' + ' '.join(f'0x{v:0{width}x},' for v in values[i:i + per_row])


def _float(value):
    # %g drops the point on whole numbers, and "1f" is not a float literal.
    text = f'{value:.9g}'
    if not any(c in text for c in '.en'):
        text += '.0'
    return text + 'f'


# MSVC caps a single string literal at 64k; stay clear of it.
MAX_TEXT_BYTES = 60000


def emit_text(entry: dict, root_directory: str):
    source = f'{root_directory}/{entry["source"]}'
    name = identifier(entry.get('name', splitext(basename(source))[0]))
    text = open(source, encoding='utf-8').read()
    # A BOM survives into the literal and breaks a leading #version.
    text = text.lstrip('﻿').replace('\r\n', '\n')
    size = len(text.encode('utf-8'))
    if size > MAX_TEXT_BYTES:
        raise CrunchError(
            f'{source}: {size} bytes exceeds the {MAX_TEXT_BYTES} byte string '
            'literal budget')
    # The raw delimiter has to be absent from the content itself.
    delimiter = 'crunch'
    while f'){delimiter}"' in text:
        delimiter += '_'
    decls = [
        f'/*! \\brief {basename(source)}, {size} bytes */',
        f'extern const std::string_view {name};',
        '',
    ]
    defs = [
        f'extern const std::string_view {name} = R"{delimiter}({text}'
        f'){delimiter}";',
        '',
    ]
    return decls, defs, source


def emit_texture(entry: dict, root_directory: str):
    source = f'{root_directory}/{entry["source"]}'
    fmt = entry.get('format', 'rgba8')
    name = identifier(entry.get('name', splitext(basename(source))[0]))
    width, height, channels, pixels = read_png(source)
    ctype, values = quantize_texture(
        pixels, channels, fmt, entry.get('channel', 'r'))
    per_row, digits = (16, 2) if ctype.endswith('u8') else (12, 4)
    decls = [
        f'/*! \\brief {basename(source)}, {width}x{height}, {fmt} */',
        f'extern const crunch::texture_desc {name}_desc;',
        f'extern const std::array<{ctype}, {len(values)}> {name}_data;',
        '',
    ]
    defs = [
        f'extern const crunch::texture_desc {name}_desc = {{',
        f'    {width}, {height}, crunch::pixel_format::{fmt}}};',
        f'extern const std::array<{ctype}, {len(values)}> '
        f'{name}_data = {{{{',
    ]
    defs += _rows(values, per_row, digits)
    defs += ['}};', '']
    return decls, defs, source


def emit_mesh(entry: dict, root_directory: str):
    source = f'{root_directory}/{entry["source"]}'
    name = identifier(entry.get('name', splitext(basename(source))[0]))
    objects = read_obj(source)
    if not objects:
        raise CrunchError(f'{source}: no drawable objects')
    (pos_min, pos_max, uv_min, uv_max), crunched = quantize_mesh(objects)

    decls = [
        f'/*! \\brief Bounding box over every object in {basename(source)} */',
        f'extern const crunch::mesh_bounds {name}_bounds;',
        '',
    ]
    defs = [
        f'extern const crunch::mesh_bounds {name}_bounds = {{',
        f'    {{{", ".join(_float(v) for v in pos_min)}}},',
        f'    {{{", ".join(_float(v) for v in pos_max)}}},',
        f'    {{{", ".join(_float(v) for v in uv_min)}}},',
        f'    {{{", ".join(_float(v) for v in uv_max)}}}}};',
        '',
    ]
    for obj_name, verts, indices in crunched:
        full = f'{name}_{identifier(obj_name)}'
        decls += [
            f'/*! \\brief {obj_name}: {len(verts)} vertices, '
            f'{len(indices) // 3} triangles */',
            f'extern const std::array<crunch::vertex, {len(verts)}> '
            f'{full}_vertices;',
            f'extern const std::array<libc_types::u16, {len(indices)}> '
            f'{full}_indices;',
            '',
        ]
        defs += [
            f'extern const std::array<crunch::vertex, {len(verts)}> '
            f'{full}_vertices = {{{{',
        ]
        for pos, normal, uv in verts:
            defs.append(
                '    {{%s}, {%s}, {%s}},' % (
                    ', '.join(_float(v) for v in pos),
                    ', '.join(_float(v) for v in uv),
                    ', '.join(f'0x{v:04x}' for v in normal)))
        defs += [
            '}};',
            f'extern const std::array<libc_types::u16, {len(indices)}> '
            f'{full}_indices = {{{{',
        ]
        defs += _rows(indices, 12, 4)
        defs += ['}};', '']
    return decls, defs, source


def write_if_changed(path: str, text: str):
    """Rewrite only on a real change; the header is a compile dependency."""
    if exists(path) and open(path).read() == text:
        return False
    makedirs(dirname(path), exist_ok=True)
    open(path, 'w').write(text)
    return True


def crunch_group(group: dict, root_directory: str, include_directory: str):
    output = f'{include_directory}/{group["output"]}'
    namespace = group.get('namespace', 'crunched')
    sources = []
    decls = []
    defs = []
    for kind, emit in (('text', emit_text), ('textures', emit_texture),
                       ('meshes', emit_mesh)):
        for entry in group.get(kind, []):
            entry_decls, entry_defs, source = emit(entry, root_directory)
            decls += entry_decls
            defs += entry_defs
            sources.append(source)

    banner = [
        f'/* Generated by toolchain/desktop/asset_crunch.py v{FORMAT_VERSION} '
        '-- do not edit. */',
        f'/* Sources: {", ".join(basename(s) for s in sources)} */',
        '',
    ]

    # The data is defined in its own translation unit; the header only
    # declares it, so including this costs nothing but the declarations.
    header = ['#pragma once', ''] + banner + [
        '#include <crunched/crunch_types.h>',
        '',
        f'namespace {namespace} {{',
        '',
    ] + decls + [f'}} // namespace {namespace}', '']

    body = banner + [
        f'#include <{group["output"]}>',
        '',
        f'namespace {namespace} {{',
        '',
    ] + defs + [f'}} // namespace {namespace}', '']

    write_if_changed(f'{include_directory}/crunched/crunch_types.h', TYPES_HEADER)
    changed = write_if_changed(output, '\n'.join(header))
    source_path = f'{splitext(output)[0]}.cpp'
    changed |= write_if_changed(source_path, '\n'.join(body))
    return output, changed


def crunch_assets(
        values,
        root_directory: str,
        include_directory: str,
        **kwargs):
    """Entry point for resource_compile.py's "crunch" key."""
    if include_directory is None:
        raise CrunchError(
            'a "crunch" resource needs --include-output to put headers in')
    for group in (values if isinstance(values, list) else [values]):
        output, changed = crunch_group(group, root_directory, include_directory)
        log('crunched' if changed else 'up to date', output)


if __name__ == '__main__':
    import json
    from argparse import ArgumentParser

    parser = ArgumentParser(__file__)
    parser.add_argument('-r', '--root', dest='root', default='.',
                        help='Directory holding resources.json and its assets')
    parser.add_argument('-o', '--output', dest='output', required=True,
                        help='Include directory to write headers into')
    args = parser.parse_args()
    VERBOSE = True
    definition = json.load(open(f'{args.root}/resources.json'))
    crunch_assets(definition['crunch'], root_directory=args.root,
                  include_directory=args.output)
