set(COFFEE_BUILD_OPENSSL OFF CACHE BOOL "")
set(COFFEE_BUILD_OPENAL OFF CACHE BOOL "")
set(COFFEE_BUILD_GLES ON CACHE BOOL "")

set(EMSCRIPTEN_ROOT_PATH ${EMSDK_ROOT}/emscripten/master/ CACHE PATH "")

set(COFFEE_GENERATE_HTML ON CACHE BOOL "")
