set(COFFEE_BUILD_OPENSSL OFF CACHE BOOL "")
set(COFFEE_BUILD_OPENAL OFF CACHE BOOL "")
set(COFFEE_BUILD_GLES ON CACHE BOOL "")

set(SDL2_LIBRARY ${NATIVE_LIB_ROOT}/Emscripten/lib/libSDL2.a CACHE FILEPATH "")
set(SDL2_INCLUDE_DIR ${NATIVE_LIB_ROOT}/Emscripten/include/SDL2/ CACHE PATH "")
set(EMSCRIPTEN_ROOT_PATH ${EMSDK_ROOT}/emscripten/master/ CACHE PATH "")

set(COFFEE_GENERATE_WASM ON CACHE BOOL "")
