set ( CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR}/out CACHE PATH "" )
set ( NATIVE_LIBRARY_DIR ${NATIVE_LIBRARY_DIR}/Maemo/${CMAKE_LIBRARY_ARCHITECTURE} )

set ( COFFEE_BUILD_GLES ON CACHE BOOL "" )
set ( COFFEE_BUILD_OPENSSL OFF CACHE BOOL "" )
set ( COFFEE_BUILD_SDL2 OFF CACHE BOOL "" )
set ( COFFEE_BUILD_ASIO OFF CACHE BOOL "" )
