set ( COFFEE_BUILD_OPENSSL OFF CACHE BOOL "" )
set ( COFFEE_BUILD_OPENAL OFF CACHE BOOL "" )
set ( COFFEE_BUILD_GLES ON CACHE BOOL "" )
set ( NATIVE_LIBRARY_DIR "/native-lib/NaCL" CACHE STRING "" )

set ( SDL2_LIBRARY "${NATIVE_LIBRARY_DIR}/lib/libSDL2.a" CACHE FILEPATH "" )
set ( SDL2_INCLUDE_DIR "${NATIVE_LIBRARY_DIR}/include/SDL2" CACHE PATH "" )
