set ( NATIVE_LIBRARY_DIR ${NATIVE_LIBRARY_DIR}/Linux/${CMAKE_LIBRARY_ARCHITECTURE} )

set ( COFFEE_BUILD_GLES ON CACHE BOOL "" )
set ( COFFEE_BUILD_GLES_20 ON CACHE BOOL "" )
set ( COFFEE_BUILD_OPENSSL OFF CACHE BOOL "" )
