set ( COFFEE_BUILD_OPENSSL OFF CACHE BOOL "" )
set ( COFFEE_BUILD_OPENAL OFF CACHE BOOL "" )
set ( COFFEE_BUILD_GLES ON CACHE BOOL "" )
set ( NATIVE_LIBRARY_DIR "/nativelib/NaCL" CACHE STRING "" )

set ( SDL2_LIBRARY "${NATIVE_LIBRARY_DIR}/lib/libSDL2.a" CACHE FILEPATH "" )
set ( SDL2_INCLUDE_DIR "${NATIVE_LIBRARY_DIR}/include/SDL2" CACHE PATH "" )
set ( SDL2_MAIN_C_FILE "${NATIVE_LIBRARY_DIR}/src/SDL_nacl_main.c" CACHE FILEPATH "" )
