set ( COFFEE_GENERATE_SNAPPY ON CACHE BOOL "" )
set ( COFFEE_GENERATE_FLATPAK ON CACHE BOOL "" )

set ( COFFEE_BUILD_GLES ON CACHE BOOL "" )
set ( COFFEE_BUILD_GLES_20 ON CACHE BOOL "" )

set ( COFFEE_BUILD_ASSIMP ON CACHE BOOL "" )
