set ( NATIVE_LIBRARY_DIR ${NATIVE_LIBRARY_DIR}/Linux/${CMAKE_LIBRARY_ARCHITECTURE} )

set ( COFFEE_BUILD_GLES ON CACHE BOOL "" )
set ( COFFEE_BUILD_OPENSSL OFF CACHE BOOL "" )

#set ( COFFEE_BUILD_SWIG_BINDING ON CACHE BOOL "" )

#set ( COFFEE_DLANG ON CACHE BOOL "" )
#set ( COFFEE_CSHARP ON CACHE BOOL "" )

#set ( SWIG_EXECUTABLE "/usr/bin/swig3.0" CACHE STRING "" )
#set ( SWIG_DIR "/usr/share/swig3.0" CACHE STRING "" )
