name: CMake Build
'on':
  push:
    branches:
    - master
    - testing
    - feature**
jobs:
  Linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        variant:
        - android.armv7a.v19
        - android.armv7a.v21
        - android.armv7a.v27
        - android.armv8a.v27
        - android.armv8a.v29
        - fedora.amd64
        - raspberry.armhf
        - ubuntu.amd64
    env:
      CONFIGURATION: Release
      BUILDVARIANT: ${{ matrix.variant }}
      ACTIONS: '1'
      MAKEFILE_DIR: toolchain/makers
      SOURCE_DIR: ${{ github.workspace }}/source
      BUILD_DIR: ${{ github.workspace }}/build
      BUILD_REPO_URI: ${{ github.repository }}
      BUILD_REPO_BRANCH: ${{ github.ref }}
      BUILD_REPO_EVENT: push
      BUILD_REPO_ID: ''
      BUILD_REPO_URL: https://github.com/${{ github.repository }}
      TRAVIS_COMMIT: ${{ github.sha }}
      TRAVIS_REPO_SLUG: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRAVIS_OS_NAME: linux
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: source
    - run: source/toolchain/ci/travis-deps.sh
      shell: sh
      name: Downloading dependencies
    - run: source/toolchain/ci/travis-build.sh
      shell: sh
      name: Building project
    - run: source/toolchain/ci/travis-deploy.sh
      shell: sh
      name: Deploying artifacts
      continue-on-error: true
  macOS:
    runs-on: macos-10.15
    strategy:
      matrix:
        variant:
        - ios.x86_64
        - osx
    env:
      CONFIGURATION: Release
      BUILDVARIANT: ${{ matrix.variant }}
      ACTIONS: '1'
      MAKEFILE_DIR: toolchain/makers
      SOURCE_DIR: ${{ github.workspace }}/source
      BUILD_DIR: ${{ github.workspace }}/build
      BUILD_REPO_URI: ${{ github.repository }}
      BUILD_REPO_BRANCH: ${{ github.ref }}
      BUILD_REPO_EVENT: push
      BUILD_REPO_ID: ''
      BUILD_REPO_URL: https://github.com/${{ github.repository }}
      TRAVIS_COMMIT: ${{ github.sha }}
      TRAVIS_REPO_SLUG: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRAVIS_OS_NAME: osx
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: source
    - run: source/toolchain/ci/travis-deps.sh
      shell: sh
      name: Downloading dependencies
    - run: source/toolchain/ci/travis-build.sh
      shell: sh
      name: Building project
    - run: source/toolchain/ci/travis-deploy.sh
      shell: sh
      name: Deploying artifacts
      continue-on-error: true
  Windows:
    runs-on: windows-2019
    strategy:
      matrix:
        variant:
        - uwp.amd64.vs19
        - win32.amd64.vs19
    env:
      AZURE_IMAGE: vs2019-win2019
      VSVERSION: '2019'
      OPENSSL_ROOT_DIR: $(Build.SourcesDirectory)/openssl-libs/
      ACTIONS: '1'
      BUILD_REPO_URI: ${{ github.repository }}
      BUILD_REPO_BRANCH: ${{ github.ref }}
      BUILD_REPO_EVENT: push
      BUILD_REPO_ID: ${{ matrix.variant }}
      BUILD_REPO_URL: https://github.com/${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CMAKE_BIN: cmake.exe
      MAKEFILE_DIR: toolchain/makers
      SAME_BUILD_DIR: '1'
      NOBUILD: '1'
      SOURCE_DIR: ${{ github.workspace }}/source
      BUILD_DIR: ${{ github.workspace }}/build
      APPVEYOR_BUILD_FOLDER: ${{ github.workspace }}/build
      APPVEYOR_REPO_NAME: ${{ github.repository }}
      APPVEYOR_REPO_COMMIT: ${{ github.sha }}
      BUILDVARIANT: ${{ matrix.variant }}
      CONFIGURATION: Debug
      PATH: $(Path);C:/Program Files/NASM
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: source
    - run: source/toolchain/ci/appveyor-deps.ps1
      shell: powershell
      name: Downloading dependencies
    - run: source/toolchain/ci/appveyor-build.ps1
      shell: powershell
      name: Configuring project
    - run: '& cmake.exe --build $env:BUILD_DIR --target install --config $env:CONFIGURATION'
      shell: powershell
      name: Building project
    - run: source/toolchain/ci/appveyor-deploy.ps1
      shell: powershell
      name: Deploying artifacts
      continue-on-error: true
