name: Formatting lint
on: [push]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@latest
            - name: Install dependencies
              run: sudo apt install cmake-format clang-format
            - name: Running clang-format
              env: 
                CI: 1
              run: ./cb format
            - name: Running cmake-format
              run: ./cb lint-cmake
            - name: Print out diff
              run: git diff
