name: Formatting lint
on: [push]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: DoozyX/clang-format-lint-action@v0.5
              with:
                  source: ./src

