name: Formatting lint
on: [push]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Running clang-format
              run: ./cb lint 2>/dev/null

