name: Formatting lint
on: [push]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Running clang-format
              env: 
                CI: 1
              run: ./cb lint

