name: Formatting lint
on: [push]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: apt install cmake-format clang-format-18
            - name: Running clang-format
              env: 
                CI: 1
              run: ./cb lint-code
            - name: Running cmake-format
              run: ./cb lint-cmake

